package com.example.taifooapplication.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import com.example.taifooapplication.R;

public class PrivacyPolicyFragment extends Fragment {

    TextView datadetails;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater,
                             @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.fragment_privacypolicy, container, false);

        datadetails = view.findViewById(R.id.datadetails);

        datadetails.setText("Disclaimer: The Company can modify this Policy unilaterally at any time without notice. Modification may be necessary, among other reasons, to maintain compliance with applicable laws and regulations or accommodate organizational changes within the Company.\n" +
                "\n" +
                "By ordering from freshshoppe.in, you are accepting the practices described in this Privacy Policy. As we continue to develop our website and the app, if any, and employ emerging technologies to improve the services we provide, this Privacy Policy may change. We encourage you to refer to this Privacy Policy to understand our current privacy policy.\n" +
                "\n" +
                "By mere use of the Website, you expressly consent to our use and disclosure of your personal information in accordance with the Privacy Policy. Privacy Policy is deemed to be incorporated into and is subject to the Terms of Service Agreement. By using the services or by otherwise giving us your information, you will be deemed to have read, understood and agreed to the practices and policies outlined in this privacy policy and agree to be bound by the privacy policy. You hereby consent to our collection, use and sharing, disclosure of your information as described in this privacy policy. We reserve the right to change, modify, add or delete portions of the terms of this privacy policy, at our sole discretion, at any time. If you do not agree with this privacy policy at any time, do not use any of the services or give us any of your information. if you use the services on behalf of someone else (such as your child) or an entity (such as your employer), you represent that you are authorised by such individual or entity to (i) accept this privacy policy on such individual’s or entity’s behalf, and (ii) consent on behalf of such individual or entity to our collection, use and disclosure of such individual’s or entity’s information as described in this privacy policy.\n" +
                "\n" +
                "A2R RETAIL (“Company” or “FRESH SHOPPE”) has created this privacy policy (“Privacy Policy” or “Policy”) to demonstrate our firm commitment to protecting information you submit. We understand that you care about how information about you is used. We are committed to protecting your privacy and your personal information. This also applies to services and products offered by FRESH SHOPPE, as well as any other applications, content or features that we may from time to time offer on our website or the app.\n" +
                "\n" +
                "This Privacy Policy describes how the Company manages personal information collected, received, or maintained. We collect information pertaining to you which may be classified as personal information and sensitive personal data or information and all other types of information through our website, other online services and other modes.\n" +
                "\n" +
                "We take utmost care to protect your privacy. This Privacy Policy pertains to the different means of how we collect your information and describes how your personal information is stored and treated.\n" +
                "\n" +
                "For the purposes of this Privacy Policy,\n" +
                "\n" +
                "The term “PI” (Personal Information) means any personal information that relates to a natural person which, either directly or indirectly, in combination with other information available or likely to be available is capable of identifying such person.\n" +
                "\n" +
                "The terms “SPI” (Sensitive Personal Information) of a person means such personal information which consists of information relating to (i) password; (ii) financial information such as bank account or credit card or debit card or other payment instrument details; (iii) physical, physiological and mental health condition; (iv) sexual orientation; (v) medical records and history; (vi) biometric information; (vii) any detail relating to the above shared with us for providing service; and (viii) any of the information received under above clauses for processing: provided that any information that is freely available or accessible in public domain or furnished under the Right to Information Act, 2005 or any other law for the time being in force shall not be regarded as SPI.\n" +
                "\n" +
                "WEBSITE:\n" +
                "\n" +
                "For the purposes of this Privacy Policy, Website means www.freshshoppe.in or any other app that may be made available by us.\n" +
                "\n" +
                "You may access and browse our website without revealing any of your Personal Information. However, while downloading any of our material which have been developed by our internal experts OR while subscribing to our newsletters OR while filling in a contact request form OR by ordering any products from our website, we may collect your Personal Information that may be necessary to help us provide better customer service.\n" +
                "This portion of the Privacy Policy applies to our website. It does not apply to any other website of any third party, even if the third-party website links to (or is linked from) our website. By accessing, using, and/or submitting information through our website, you consent to the practices described in this Privacy Policy with regard to the information collected thereby as described herein. If you do not agree with this Privacy Policy, you must delete all cookies from your browser cache after visiting the website and refrain from visiting or using the website.\n" +
                "HOW DOES WE USE COOKIES\n" +
                "\n" +
                "We want you to be aware that certain online tools exist to help us serve and recognize you when you visit our website. For your convenience, to help us personalize your experience or better serve your needs, we may receive and store certain types of information when you visit our website. These are called ‘cookies.’ The cookies may be placed on your computer when you visit our site. Our web server automatically recognizes non-personally, identifiable information only, e.g., domain type, browser version, and service provider for each of the visitors on our site. Cookies do not provide any personal information but they allow us to understand how users navigate to and around our website, view product pages, access content and make purchases. We use cookies placed on your computer's hard drive through your web browser to enable our systems to recognize your browser during your visit and when you return to our site. For instance, when you are ready to purchase an item, a cookie allows our site to ‘remember’ you have added the item to your shopping cart.\n" +
                "To browse the website only, you are not required to provide any personal information. However, we may gather non-personally-identifiable information. Like most commercial websites, we utilize “cookies” and other technologies to collect non-personally-identifiable information on visitors to the website. Cookies allow web servers to recognize the computer used to access a website. Cookies store information accessed through your browser to streamline activities on related web sites, and make the online experience easier and more personalized. Information gathered through cookies and web-server log files may include information such as the date and time of visits, the pages viewed, IP addresses, links to/from any page, and time spent at a site.\n" +
                "Information collected from website submissions will be used for Company’s internal business purposes, including its investigations, sales, and marketing. We may use IP addresses for purposes such as calculating usage levels, diagnosing server problems and administering the services. We may also derive your approximate location from your IP address. The website may include options for visitors to submit information to Company, for example, while requesting information about a product/service, downloading an article, etc. Such forms may provide the option of submitting personal information, such as your name, job title, company, email address, or phone number. In addition, when submitting information on a Website, your submission will be associated with the IP address you are then using, which is automatically assigned to your computer by your Internet Service Provider. If you are using one of the market leading browsers and are uncomfortable accepting cookies from our website, you may erase and/or disable the acceptance of cookies in your browsers administrative tools. Disabling your browser in this manner may result in a compromised experience of www.nvday.in or other websites you regularly visit.\n" +
                "We use cookie data to measure site traffic and usage activity for purposes of improving and enhancing the functionality of the Website, to look for possible fraudulent activity, to better understand the sources of traffic and transactions on the Website, and/or to serve targeted advertisements. Cookies also allow our servers to remember your account information for future visits and to provide personalized and streamlined information across related pages on the Website. You can choose to disable cookies for the Website but this may substantially limit your ability to use our Website. The use of cookies by our partners, affiliates, tracking utility company, or service providers is not covered by this Policy. We do not have access or control over these cookies.\n" +
                "Company takes measures to maintain the security of its website visitor information, does not license or sell such information to anyone, and will only share such information with a third party who has agreed to keep such information confidential and maintain the security thereof, and only for the purposes of facilitating one of the uses described herein on behalf of Company.\n" +
                "Our company contracts under an agreement of confidentiality with Google Analytics, a service provider that provides data collection and reports regarding our customers' activities on our site to help us better understand consumer patterns for freshshoppe.in. Google Analytics may use cookies on our behalf and may receive information about your browsing and buying activity so that we may continue to refine the site, improve it and better serve you. Google Analytics may store member ID, city, state, zip code, and email addresses on our behalf. Google Analytics analyzes the information it collects on our behalf and returns it back to us through a secure web connection. Under no circumstances may Google Analytics use your information other than in connection with providing services to us to make our site more useful and efficient. freshshoppe.in does not permit Google Analytics to collect credit card, username or password information.\n" +
                "HOW DOES COMPANY COLLECT AND USE INFORMATION\n" +
                "\n" +
                "Visitors to our site may choose to submit their name, email address and/or other information so that they can learn more about our services, register to take part in a Company sponsored event, or participate in a survey among other things.\n" +
                "In order to use Company's products and services, you may be required to register as a user. From time to time, we may use your email address to send you information and keep you informed of products and services in which you might be interested. You will always be provided with an opportunity to opt out of receiving such emails. Your contact information may also be used to reach you regarding issues concerning your use of our site, including changes to this privacy policy.\n" +
                "Information may be used for Company’s legitimate business interests in connection with your use of the services, including to respond to user inquiries and fulfil user requests, complete transactions, provide customer service, send administrative information, and to personalize user experience with the services. We may use information to better understand our users in general and to improve the content and functionality of the services. We may use information to contact you in the future to tell you about services, promotions, opportunities, and other general information about Company we believe will be of interest to you. We may use information to investigate and prosecute potential breaches of Company security or license agreements.\n" +
                "The information we collect from you is also used to provide emails relevant to you. In addition, we may use such information to register you, confirm your order, your delivery information, respond to your customer service inquiries or requests and communicate other benefits and features. When you provide us with personal information about other people, (for example, you may provide us with a name and address for a merchandise gift recipient), we use that information for the purposes of processing the delivery and, in some cases, to communicate with the intended recipient with information pertaining to the status of the delivery. We rely on you to obtain the intended recipient's consent to our use of their personal information for these limited purposes.\n" +
                "Please know that Company does not sell, distribute, or give your personal information to any third party without your knowledge and consent except to provide products or services in which you have expressly displayed an interest, when you have given Company your permission, or under the following circumstances:\n" +
                "When working with contracted outsourcing partners who work on behalf of Company. These partners are subject to strict confidentiality agreements.\n" +
                "Additionally, these companies are not extended any independent right to share this information with their partners.\n" +
                "If we should have to respond to legal action, subpoenas, court orders or legal process, or to establish or exercise our legal rights or defend against legal claims.\n" +
                "We believe that there is a necessity to share information in order to investigate, defend or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, or as otherwise required by law.\n" +
                "We may transfer your information in case of any acquisition or merger within the company. This transition will take place with full disclosure of this Privacy Policy and the commitments expressed herein.\n" +
                "We use non-personally identifiable information to analyse site usage (such as aggregated information on the pages visited by our users), which allows us to improve the design and content of our web site.\n" +
                "We also hold your contact information in our marketing database and occasionally we may contact you with our updates, newsletters, greetings, events and seminars that we hold, which we refer to as Marketing Communications.\n" +
                "In the ordinary course, we use personal information you provide to respond to your inquiry or process a recruitment request application form you have consented to and completed on our web site. We also use this information for internal purposes to send Marketing Communications as mentioned above.\n" +
                "We will not contact you about other matters, unless you specifically request it, nor will we share, rent, or sell your personally identifiable information outside the Company, except where we are required to share your information with any third parties to provide services to you.\n" +
                "Company takes data security seriously and provides access permission to systems that contains such data only on a need to know basis. Company may occasionally partner with other third party companies in web-based promotions. However, Company shall not be liable for any personal information submitted to external vendors or to any website linked to this site. Company also recommends that any website visitor, accessing the www.nvday.in website as an employee of a company, abide by the privacy practices and security guidelines of the corporations they represent. Company’s website team recognizes that the receipt, transmission, distribution, or propagation of unwanted emails (Spam) as a major concern. We will abide by all anti-Spam legal regulations when emailing any and all information out from Company.\n" +
                "However, we cannot guarantee the privacy of personal information you transmit over the web or that may not be securely transmitted.\n" +
                "All orders are processed through the freshshoppe Shopping Cart via PayTM and razorpay. Credit card information collected on this website is stored on both Pay TM and razorpay secure sites and are available to freshshoppe.in for up to 30 days. Delivery and e-mail information is also stored.\n" +
                "Your information collected for PayTM and razorpay’s secure online payment system is governed by PayTM’s privacy policy and razorpay’s privacy policy. PayTM and Razor pay would request information from you on our order form. To buy from us, you must provide contact information (like name and delivery address) and financial information (like credit card number, expiration date). This information is used by PayTM and razorpay for billing purposes and to fulfil your delivery. If they have trouble processing an order, they will use this information to contact you by e-mail.\n" +
                "We contract with third parties to serve ads on our behalf across the internet and sometimes on this site. They may collect anonymous information about your visits to our website, and your interaction with our products and services. They may also use information about your visits to this and other websites to target advertisements for goods and services. This anonymous information is collected through the use of a pixel tag, which is an industry standard technology used by most major websites. No personally identifiable information is collected or used in this process. They do not know the name, phone number, address, e-mail address, or any personally identifying information about the user.\n" +
                "We may disclose to third party services certain personally identifiable information i.e, information you provide us such as name, email, mobile phone number, Information we collect as you access and use our service, including device information, location and network carrier. This information is shared with third party service providers so that we can, personalize the app for you and perform behavioral analytics.\n" +
                "If you would like Company to delete/edit/remove personal information collected about you, please send an email to freshshoppe.india@gmail.com with ‘REMOVE’ mentioned in the subject line.\n" +
                "COMPANY PRODUCTS AND SERVICES\n" +
                "\n" +
                "For the purpose of providing our products and services as well as for internal administrative purposes, we or any of our third party service providers may receive, collect, store or share PI or SPI (both terms as defined above).\n" +
                "By accessing our website or availing any product or services,\n" +
                " \n" +
                "you hereby grants approval and consents to the Company and its personnel to receive, collect, retain, store, share, disclose (including to third party service providers) or otherwise use the PI or SPI of the client/clients personnel as may be required for the purpose of the engagement or administrative purposes or thereafter for record purposes.\n" +
                "Notwithstanding the above, there shall be no restriction on the Company to share or disclose PI or SPI as may be required under any applicable law (including to third parties by an order under the law) or to any governmental, statutory or regulatory authority or agency.\n" +
                "INFORMATION SECURITY PRACTICES AND PROCEDURES\n" +
                "\n" +
                "The Company limits access to personal information to authorized firm employees, associates, partners and officers, our service providers are held to stringent standards of privacy. The company maintains physical, electronic and procedural safeguards to protect the information against loss, misuse, damage or modification and unauthorized access or disclosure. Some of the other central features of our information security program are:\n" +
                " \n" +
                "The use of specialized technology such as firewalls.\n" +
                "Testing of the security and operability of products and services by the IT department before they are introduced to the Internet, as well as ongoing scanning for publicly known vulnerabilities in the technology.\n" +
                "Implementing controls to identify, authenticate and authorize access to various systems or sites.\n" +
                "Restricting use of external data devices on Company’s systems.\n" +
                "Providing Company’s personnel with relevant training and continually updating our security practices in light of new risks and developments in technology.\n" +
                "GRIEVANCES\n" +
                "\n" +
                "Should you have any grievances about the processing of your personal information, you may contact Shaikh Tousif Ahmed with respect to Data Protection and Privacy related complaints at freshshoppe.india@gmail.com. All email messages sent to and from www.nvday.in may be monitored with the objective of ensuring compliance with internal policies and to protect our business.");

        return view;
    }
}
